# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dziedzicgrzegorz < Formula
  desc ""
  homepage "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v0.1.0/Tic-Tac-Toe_0.1.0_darwin_all.tar.gz"
    sha256 "35a8efdfaa4b3dde83967539d9e9c3a653e14c5ed63c5aac8f0f6bc59291eb3c"

    def install
      bin.install "Tic-Tac-Toe"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v0.1.0/Tic-Tac-Toe_0.1.0_linux_amd64.tar.gz"
        sha256 "f586ea3cf3c50204316d4bc356c278224591c82070fdc45733d9bb31ee3e6046"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v0.1.0/Tic-Tac-Toe_0.1.0_linux_arm64.tar.gz"
        sha256 "8e99d5c45cc9c775b7e8a0005922e08b66aff4bf66839e52873a6def01973c69"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
  end
end
