# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dziedzicgrzegorz < Formula
  desc ""
  homepage "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.0/Tic-Tac-Toe_1.0.0_darwin_all.tar.gz"
    sha256 "ac9ba5ee3fb9bef415897a9a778511a7624b158696c719907a8131c37b5299e2"

    def install
      bin.install "Tic-Tac-Toe"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.0/Tic-Tac-Toe_1.0.0_linux_amd64.tar.gz"
        sha256 "fd61df513e91fff9062ae0bf0952d455e60bdb2949498ae90ea279980821918a"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.0/Tic-Tac-Toe_1.0.0_linux_arm64.tar.gz"
        sha256 "d814a9546767be2b6d495ddb21869591e907e27bd44df9f78e064659adc89290"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
  end
end
