# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dziedzicgrzegorz < Formula
  desc ""
  homepage "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe"
  version "1.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.1/Tic-Tac-Toe_1.0.1_darwin_all.tar.gz"
    sha256 "437454e9ce38b1df21df61445d326975f4afcf7744ab32509e1896890e983d45"

    def install
      bin.install "Tic-Tac-Toe"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.1/Tic-Tac-Toe_1.0.1_linux_amd64.tar.gz"
        sha256 "8256a29e74778bb6adf93d9d4bd3fa20cd4621f10578255f023675d66fac982a"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DziedzicGrzegorz/Tic-Tac-Toe/releases/download/v1.0.1/Tic-Tac-Toe_1.0.1_linux_arm64.tar.gz"
        sha256 "8f69adb4874e9f4c53378ca7f917e3dc8ce463abb9598827a8280e5eafb47e37"

        def install
          bin.install "Tic-Tac-Toe"
        end
      end
    end
  end
end
